#!/bin/sh

# Set Session Name
SESSION="Workshop"
SESSIONEXISTS=$(tmux list-sessions | grep $SESSION)

# Only create tmux session if it doesn't already exist
if [ "$SESSIONEXISTS" = "" ]; then
  # Start New Session with our name
  tmux new-session -d -s $SESSION -n Main

  tmux split-window -h -p 80 -t $SESSION:0
  tmux split-window -h -p 20 -t $SESSION:0.1
  tmux split-window -v -t $SESSION:0.1

  tmux send-keys -t $SESSION:0.0 'watch -c gpustat --color' C-m
  tmux send-keys -t $SESSION:0.3 'htop -d 20 -u lhj' C-m
fi

# Attach Session, on the Main window
tmux attach-session -t $SESSION:0
